alias ..="cd .."
alias ...="cd ../.."
alias in="sudo dnf install"
alias up="sudo dnf update -y"
alias se="dnf search"
alias remo="sudo dnf remove"
alias newed="ssh-keygen -o -a 100 -t ed25519"
alias newrsa="ssh-keygen -t rsa -b 4096 -C "omaryscott@gmail.com"
