alias ..="cd .."
alias ...="cd ../.."
alias vim="nvim"
alias in="sudo eopkg install"
alias up="sudo eopkg upgrade -y"
alias se="eopkg search"
alias remo="sudo eopkg remove"
alias newkey="ssh-keygen -t rsa -b 4096 -C \"omaryscott@gmail.com\""
alias xpad="sudo xboxdrv -ds --mimic-xpad-wireless"
alias pipup="pip3 list --outdated --format=legacy | cut -d' ' -f1 | xargs -n1 pip3 install -U --user"
