alias ..="cd .."
alias ...="cd ../.."
alias vim="nvim"
alias in="sudo apt install"
alias up="sudo apt update -y"
alias upd="sudo apt upgrade -y"
alias se="apt search"
alias remo="sudo apt remove"
alias newkey="ssh-keygen -t rsa -b 4096 -C \"omaryscott@gmail.com\""
alias pipup="pip list --outdated --format=legacy | cut -d' ' -f1 | xargs -n1 pip install -U --user"
