alias ..="cd .."
alias ...="cd ../.."
alias in="sudo pacman -S"
alias up="sudo pacman -Syu"
alias se="pacman -Ss"
alias orf="sudo pacman -Rns (pacman -Qtdq)"
alias remo="sudo pacman -R"
alias newkey="ssh-keygen -t ed25519 -C \"omaryscott@gmail.com\""
alias pissh="ssh pi@192.168.1.178"
alias vid="mpv --ytdl-format=22 --fs (wl-paste) || mpv --fs (wl-paste)"
alias novid="mpv --no-video (wl-paste)"
