alias ..="cd .."
alias ...="cd ../.."
alias in="sudo dnf install"
alias up="sudo dnf update -y"
alias fup="flatpak update -y"
alias se="dnf search"
alias remo="sudo dnf remove"
alias newkey="ssh-keygen -t rsa -b 4096 -C \"omaryscott@gmail.com\""
alias pissh="ssh pi@192.168.1.178"
alias pipup="pip list --outdated --format=legacy | cut -d' ' -f1 | xargs -n1 pip install -U --user"
alias vid="mpv --ytdl-format=22 --fs (xclip -o) || mpv --fs (xclip -o)"
