alias ..="cd .."
alias ...="cd ../.."
alias ls="lsd"
alias l="ls -l"
alias la="ls -a"
alias lla="ls -la"
alias lt="ls --tree"
alias rm="rip"
alias cat="bat"
alias in="sudo dnf install"
alias up="sudo dnf update -y"
alias fup="flatpak update -y"
alias se="dnf search"
alias remo="sudo dnf remove"
alias newkey="ssh-keygen -t ed25519 -C \"omaryscott@gmail.com\""
alias vid="mpv --ytdl-format=22 --fs (xclip -o) || mpv --fs (xclip -o)"
alias clipkey="xclip -selection clipboard < ~/.ssh/id_ed25519.pub"
